# Generated by Django 5.2.5 on 2025-10-08 11:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sewing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.CharField(blank=True, max_length=120, null=True)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='sewing.order')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_warehouse', to='stock.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sewing.order')),
                ('total_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='stock.totalentry')),
            ],
        ),
        migrations.CreateModel(
            name='AccessoryStockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sewing.accessory')),
                ('total_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_stock_entries', to='stock.totalentry')),
            ],
        ),
        migrations.AddField(
            model_name='totalentry',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_entries', to='stock.warehouse'),
        ),
        migrations.CreateModel(
            name='AccessoryStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sewing.accessory')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_warehouse', to='stock.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='StockEntryVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('stock_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='stock.stockentry')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sewing.ordervariant')),
            ],
            options={
                'unique_together': {('stock_entry', 'variant')},
            },
        ),
        migrations.CreateModel(
            name='StockVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_variants', to='stock.stock')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sewing.ordervariant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('stock', 'variant'), name='uniq_stock_variant'), models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='qty_gte_0')],
            },
        ),
    ]
