# Generated by Django 5.2.5 on 2025-10-08 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sewing', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sort_1', models.PositiveIntegerField(blank=True, null=True)),
                ('sort_2', models.PositiveIntegerField(blank=True, null=True)),
                ('defect_quantity', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_1', models.PositiveIntegerField(blank=True, null=True)),
                ('sort_2', models.PositiveIntegerField(blank=True, null=True)),
                ('defect_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('line_daily', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='production.daily')),
            ],
        ),
        migrations.CreateModel(
            name='MonthPlaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030)])),
                ('month', models.CharField(choices=[('01', 'Yanvar'), ('02', 'Fevral'), ('03', 'Mart'), ('04', 'Aprel'), ('05', 'May'), ('06', 'Iyun'), ('07', 'Iyul'), ('08', 'Avgust'), ('09', 'Sentabr'), ('10', 'Oktyabr'), ('11', 'Noyabr'), ('12', 'Dekabr')], max_length=2)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('day_planing', models.CharField(max_length=100)),
                ('planing_quantity', models.IntegerField(blank=True, null=True)),
                ('fact_quantity', models.IntegerField(blank=True, null=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='MonthPlaningOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planed_quantity', models.IntegerField()),
                ('stock_quantity', models.IntegerField(blank=True, null=True)),
                ('fact_quantity', models.IntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('month_planing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_planing_order', to='production.monthplaning')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sewing.order')),
            ],
        ),
        migrations.CreateModel(
            name='NormCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sort_1', models.PositiveIntegerField(blank=True, null=True)),
                ('total_sort_2', models.PositiveIntegerField(blank=True, null=True)),
                ('total_defect', models.PositiveIntegerField(blank=True, null=True)),
                ('norm', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sewing.order')),
                ('order_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sewing.ordervariant')),
            ],
        ),
        migrations.CreateModel(
            name='LineOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_1', models.IntegerField()),
                ('sort_2', models.IntegerField(blank=True, null=True)),
                ('defect_quantity', models.PositiveIntegerField(default=0)),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_line', to='production.line')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_line_orders', to='production.normcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_lines', to='stock.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sort_1', models.PositiveIntegerField(blank=True, null=True)),
                ('total_sort_2', models.PositiveIntegerField(blank=True, null=True)),
                ('total_defect', models.PositiveIntegerField(blank=True, null=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.productionline')),
            ],
        ),
        migrations.AddField(
            model_name='normcategory',
            name='production_norm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='norm_category', to='production.productionnorm'),
        ),
        migrations.AddField(
            model_name='line',
            name='production_norm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='production.productionnorm'),
        ),
        migrations.CreateModel(
            name='ProductionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030)])),
                ('month', models.CharField(choices=[('01', 'Yanvar'), ('02', 'Fevral'), ('03', 'Mart'), ('04', 'Aprel'), ('05', 'May'), ('06', 'Iyun'), ('07', 'Iyul'), ('08', 'Avgust'), ('09', 'Sentabr'), ('10', 'Oktyabr'), ('11', 'Noyabr'), ('12', 'Dekabr')], max_length=2)),
                ('total_sort_1', models.PositiveIntegerField(default=0)),
                ('total_sort_2', models.PositiveIntegerField(default=0)),
                ('total_defect', models.PositiveIntegerField(default=0)),
                ('total_norm', models.PositiveIntegerField(default=0)),
                ('day', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='productionnorm',
            name='production_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_norm', to='production.productionreport'),
        ),
        migrations.CreateModel(
            name='ProductionCategorySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norm', models.PositiveIntegerField(default=0)),
                ('actual', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sewing.sewingcategory')),
                ('production_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_summaries', to='production.productionreport')),
            ],
        ),
        migrations.AddField(
            model_name='daily',
            name='production_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_report', to='production.productionreport'),
        ),
        migrations.CreateModel(
            name='LineDailyOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sort_1', models.IntegerField(blank=True, null=True)),
                ('sort_2', models.IntegerField(blank=True, null=True)),
                ('defect_quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('norm_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_outputs', to='production.normcategory')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_outputs', to='production.productionline')),
            ],
            options={
                'unique_together': {('line', 'norm_category', 'date')},
            },
        ),
    ]
