# Generated by Django 5.2.5 on 2025-10-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthplaningorder',
            name='norm_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
