# Generated by Django 5.2.5 on 2025-09-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionreport',
            name='total_quantity',
        ),
        migrations.AddField(
            model_name='productionreport',
            name='total_defect',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='total_sort_1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='total_sort_2',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
