# Generated by Django 5.2.5 on 2025-10-08 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='accessories/')),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, choices=[('KG', 'Кг'), ('SHT', 'Шт'), ('M', 'Метр')], default='Шт', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('article', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='brands/')),
            ],
        ),
        migrations.CreateModel(
            name='PackagingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('norm', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SewingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('norm', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sewing.accessory')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_link', to='sewing.article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='accessories',
            field=models.ManyToManyField(related_name='articles', through='sewing.ArticleAccessory', to='sewing.accessory'),
        ),
        migrations.AddField(
            model_name='article',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sewing.brand'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sewing.brand'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_detail', to='sewing.article')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sewing.specification')),
            ],
        ),
        migrations.CreateModel(
            name='OrderVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_link', to='sewing.order')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='packaging_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sewing.packagingcategory'),
        ),
        migrations.AddField(
            model_name='article',
            name='sewing_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sewing.sewingcategory'),
        ),
    ]
