# Generated by Django 5.2.5 on 2025-09-29 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sewing', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPackaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_packaging', to='sewing.order')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_packaging_warehouse', to='stock.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='StockPackagingVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_1', models.IntegerField(default=0)),
                ('sort_2', models.IntegerField(default=0)),
                ('stock_packaging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_packaging_variants', to='packaging.stockpackaging')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sewing.ordervariant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('stock_packaging', 'variant'), name='uniq_stock_packaging_variant'), models.CheckConstraint(condition=models.Q(('sort_1__gte', 0), ('sort_2__gte', 0)), name='packaging_qty_gte_0')],
            },
        ),
    ]
